# Dockerfile V6.0 (El "Plan PHP 8.0")

# 1. ¡LA CLAVE! Usamos PHP 8.0, la versión para la que se hizo tu composer.lock
FROM php:8.0-apache

# 2. Instalamos las dependencias del sistema (las mismas que antes)
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zlib1g-dev \
    libzip-dev \
    && rm -rf /var/lib/apt/lists/*

# 3. Instalamos Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# 4. Instalamos la extensión gRPC (requerida por Firestore)
#    (pecl la instalará para PHP 8.0)
RUN pecl install grpc
RUN docker-php-ext-enable grpc

# 5. Establecemos el directorio de trabajo
WORKDIR /var/www/html

# 6. Copiamos AMBOS archivos. ¡Ahora SÍ queremos usar el .lock!
COPY composer.json composer.lock ./

# 7. Ejecutamos 'install'. Esto leerá tu 'composer.lock' (que pide Firebase 6)
#    y funcionará, porque estamos en un entorno PHP 8.0.
RUN composer install --no-dev --optimize-autoloader 

# 8. Copiamos el RESTO de nuestra aplicación
COPY . .

# 9. Arreglamos los permisos (evita error 403)
RUN chown -R www-data:www-data /var/www/html